<RootWidget>:
# this is the rule for your root widget, defining it's look and feel.
    ActionBar:
    #this is the auto provided ActionBar with some menus. Replace it with your
    #app structure
        pos_hint: {'top':1}
        ActionView:
            use_separator: True
            ActionPrevious:
                text: ''
                split_str: ''
                title: 'Action Bar'
                with_previous: False


