<MyLayout>:
	angle: 0
	angle_shift: 0
	angle_wide: 240
	cols: 4
	padding: [10,10]
	canvas:
		Color:
			rgba: 1,0.5,0.9,1
		Rectangle:
			pos: self.pos
			size: self.size
	RelativeLayout:
		canvas:
			Color:
				rgba: 1,0,0,0.5
			Rectangle:
				pos: 0,0
				size: self.size
			Color:
				rgba: 1,1,1,1
			Ellipse:
				pos: 0,0
				size: self.size
				angle_start: root.angle + root.angle_shift
				angle_end: root.angle + root.angle_shift + root.angle_wide
	RelativeLayout:
		canvas:
			Color:
				rgba: 1,1,0,0.5
			Rectangle:
				pos: 0,0
				size: self.size
			Ellipse:
				pos: 0,0
				size: self.size
				angle_start: root.angle + root.angle_shift + 360/8
				angle_end: root.angle + root.angle_shift + root.angle_wide + 360/8
	RelativeLayout:
		canvas:
			Color:
				rgba: 1,1,1,0.5
			Rectangle:
				pos: 0,0
				size: self.size
			Ellipse:
				pos: 0,0
				size: self.size
				angle_start: root.angle + root.angle_shift + 360/8*2
				angle_end: root.angle + root.angle_shift + root.angle_wide + 360/8*2
	RelativeLayout:
		canvas:
			Color:
				rgba: 0,1,1,0.5
			Rectangle:
				pos: 0,0
				size: self.size
			Ellipse:
				pos: 0,0
				size: self.size
				angle_start: root.angle + root.angle_shift + 360/8*3
				angle_end: root.angle + root.angle_shift + root.angle_wide + 360/8*3
	RelativeLayout:
		canvas:
			Color:
				rgba: 1,1,1,0.5
			Rectangle:
				pos: 0,0
				size: self.size
			Ellipse:
				pos: 0,0
				size: self.size
				angle_start: root.angle + root.angle_shift + 360/8*4
				angle_end: root.angle + root.angle_shift + root.angle_wide + 360/8*4
	RelativeLayout:
		canvas:
			Color:
				rgba: 1,0,1,0.5
			Rectangle:
				pos: 0,0
				size: self.size
			Ellipse:
				pos: 0,0
				size: self.size
				angle_start: root.angle + root.angle_shift + 360/8*5
				angle_end: root.angle + root.angle_shift + root.angle_wide + 360/8*5
	RelativeLayout:
		canvas:
			Color:
				rgba: 0.5,1,0,0.5
			Rectangle:
				pos: 0,0
				size: self.size
			Ellipse:
				pos: 0,0
				size: self.size
				angle_start: root.angle + root.angle_shift + 360/8*6
				angle_end: root.angle + root.angle_shift + root.angle_wide+ 360/8*6
	RelativeLayout:
		canvas:
			Color:
				rgba: 1,0,0.5,0.5
			Rectangle:
				pos: 0,0
				size: self.size
			Ellipse:
				pos: 0,0
				size: self.size
				angle_start: root.angle + root.angle_shift + 360/8*7
				angle_end: root.angle + root.angle_shift + root.angle_wide + 360/8*7
	FloatLayout:
		Button:
			canvas:
				Color:
					rgba: 0.5,0.5,0.5,0.5
				Rectangle:
					pos: self.pos
					size: self.size
			text: 'Change Angle'
			center_x: root.center_x
			center_y: root.center_y
			size_hint: None, None
			on_press: root.angle_shift += 20
		