# ex42.kv

<SquareWidget>:
    size: 250,250
    canvas:
        Color:
            rgb: [1,1,0]
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
			rgb: 1,0,0
					
    Button:
		text: 'AI Core I7'
		pos: root.width / 4, root.height / 4
		size_hint: None, None
		size: root.width / 2, root.height / 2
<Ex42>:
    canvas:
        Color:
            rgb: .5,.5,.5
        Rectangle:
            size: self.size
            pos: self.pos
    ScatterWidget:
        id: square_widget_id
        SquareWidget:
    Label:
        text: 'Rotation: ' + str(square_widget_id.rotation)
        size_hint: .1,.1
        pos: 500,100
    Label:
        text: 'Scale: ' + str(square_widget_id.scale)
        size_hint: .1,.1
        pos: 500,200
    Label:
        text: 'Position: ' + str(square_widget_id.pos)
        size_hint: .1,.1
        pos: 500,300
